title: Site

tabs:
  pages:
    label: Contenu
    sections:
      principales:
        label: Pages principales
        type: pages
        query: site.children.listed.not(kirby.collection("slashpages"))

      slashpages:
        label: Slash pages
        type: pages
        query: site.children.filterBy("slash", "true")

      autres:
        label: Autres pages
        type: pages
        query: site.children.unlisted.not(kirby.collection("slashpages"))


  header:
    label: Header
    fields:
      mainNav:
        label: Navigation principale
        type: pages

  footer:
    label: Footer
    fields:
      footerNav:
        label: Navigation du footer
        type: pages

  all:
    label: Toutes les pages
    fields:
      pages:
        type: pages
        layout: cards
        size: small
