title: Site



tabs:
  pages:
    label: Contenu
    sections:
      pages:
        type: pages
        layout: cards

  header:
    label: Header
    fields:
      mainNav:
        label: Navigation principale
        type: pages

  footer:
    label: Footer
    fields:
      footerNav:
        label: Navigation du footer
        type: pages
